default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_520_ci
  reconnect: false
  pool: 5
  socket: <%= ENV['MYSQL_SOCKET'] || '' %>

development:
  <<: *default
  database: valetbike_development
  username: root
  password: rootroot

test:
  <<: *default
  database: valetbike_test
  username: root
  password: rootroot

production:
  <<: *default
  database: valetbike_production
  username: root
  password: rootroot
